### ISSUE TITLE
Some OpenMP directives are not highlighted

### ISSUE THREAD

**Issue by pbregener** [tomedunn/language-openmp#1]
While `!$omp end task` gets highlighted nicely, `!$omp task` does not. Same for `single` and `workshare`.

**Comment by tomedunn** [comment]
Thanks for posting! This should fix the issue. Let me know if it still needs some work.

**Comment by pbregener** [comment]
Great, thanks for the quick fix! While going through more Fortran/OpenMP code, I also found these directives that currently don't get highlighted:

``` fortran
!$omp threadprivate
!$omp sections
```

Mind creating a (patch) release for this?

**Comment by tomedunn** [comment]
I'll try to put a quick patch together tonight after I get home. In the future feel free to open new issues. I don't use Atom that much for programming in Fortran/OpenMP so there are bound to be lots of obvious issues out there to be discovered. Any and all feedback on these things is super useful so keep them coming and I'll do my best to patch them quickly. :smile:

**Comment by pbregener** [comment]
Awesome, thanks! :)
